# Generated by Django 6.1.1 on 2026-09-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING_OTP', 'در انتظار OTP'), ('OTP_VERIFIED', 'OTP تأیید شده'), ('TOKEN_ISSUED', 'توکن صادر شده'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('CANCELLED', 'لغو شده')], default='PENDING_OTP', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='adminpanel.adminrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('url_secret_hash', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('REVOKED', 'لغو شده')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accesses', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='adminpanel.adminrequest')),
            ],
        ),
    ]
