# Generated by Django 6.1.1 on 2026-09-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_product_id', models.PositiveBigIntegerField(verbose_name='شناسه محصول')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت حذف')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_deletion_logs', to=settings.AUTH_USER_MODEL, verbose_name='حذف توسط')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لاگ حذف محصول',
                'verbose_name_plural': 'لاگ حذف محصولات',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
