# Generated by Django 6.1.1 on 2026-09-20 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_productdeletionlog'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRecordLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_record_locks', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_record_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قفل رکورد کاتالوگ',
                'verbose_name_plural': 'قفل\u200cهای رکورد کاتالوگ',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='adminpanel__content_b2ba8e_idx'), models.Index(fields=['last_activity'], name='adminpanel__last_ac_6fce45_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_catalog_record_lock')],
            },
        ),
    ]
